### ISSUE TITLE
Bug with rangerequestcheck

### ISSUE THREAD

**Issue by brendanheywood** [catalyst/moodle-tool_heartbeat#111]
Exception - Cannot access protected property tool_heartbeat\check\rangerequestcheck::$component

**Comment by matthewhilton** [comment]
Encountered this issue in Totara 12. 
Changed `lib/classes/check/manager.php` line 82 from 
`$check->component = $plugintype .  '_' . $plugin;`
to
`$check->set_component($plugintype .  '_' . $plugin);`
Full stack trace:
```
Exception - Cannot access protected property tool_heartbeat\check\rangerequestcheck::$component

Debug info:
Error code: generalexceptionmessage
Stack trace:
line 82 of /lib/classes/check/manager.php: Error thrown
line 56 of /lib/classes/check/manager.php: call to core\check\manager::get_performance_checks()
line 72 of /lib/classes/check/table.php: call to core\check\manager::get_checks()
line 35 of /report/performance/index.php: call to core\check\table->__construct()
```

The check API is moodle is using the correct `set_component` method - so this bug is unlikely due to check api or heartbeat and just with a specific backport of the check api to totara.

**Comment by TomoTsuyuki** [comment]
The issue has been fixed in
https://tracker.moodle.org/browse/MDL-72924
which is deployed to Moodle 3.10+.
For older version of Moodle or Totara, need to backport to solve the issue.
https://github.com/moodle/moodle/commit/086878c5417a5ffd5950ea303a5c505a9803ff22
