### ISSUE TITLE
Split stable version numbering and force master to not progress higher than the stable

### ISSUE THREAD

**Issue by brendanheywood** [catalyst/moodle-tool_heartbeat#159]
We haven't done this before but I think a unit test would be good here to make sure version is only ever a small increment (hard to test?) and never is higher than 2023102400 (or whenever the stable was forked)

**Comment by matthewhilton** [comment]
Not sure how you could unit test this. Moodle unit tests wouldn't know since they don't care about git. CI could maybe test it, but its a bit of a rabbit hole IMO since there are probably a ton of exceptions to the rule.

I'm leaning towards maybe:
1. Updating the readme to be clearer about this
2. Adding a pull request template with a checkbox for 'i have checked the version numbers are correct' https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/creating-a-pull-request-template-for-your-repository so devs are aware when they make prs

**Comment by matthewhilton** [comment]
This has been done by https://github.com/catalyst/moodle-tool_heartbeat/pull/161 and https://github.com/catalyst/moodle-tool_heartbeat/pull/160
